<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PustakaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pustaka = [
            // Teori
            [
                'title' => 'Calculus Volume 1',
                'slug' => 'calculus_volume_1',
                'url' => 'https://drive.google.com/file/d/1xHSd0HZuTxm2OAGuOUM8JqvMh-FHj5nD/view',
                'isbn' => '9781947172135',
                'penulis' => 'Gilbert Strang',
                'penerbit' => 'OpenStax',
                'tahun_terbit' => '2016',
                'abstrak' => 'Kalkulus dirancang untuk mata kuliah kalkulus umum dua atau tiga semester, dengan menggabungkan fitur-fitur inovatif untuk meningkatkan pembelajaran mahasiswa. Buku ini memandu mahasiswa melalui konsep-konsep inti kalkulus dan membantu mereka memahami bagaimana konsep-konsep tersebut diterapkan pada kehidupan mereka dan dunia di sekitar mereka. Karena sifat materinya yang komprehensif, kami menawarkan buku ini dalam tiga jilid untuk fleksibilitas dan efisiensi. Volume 1 mencakup fungsi, limit, turunan, dan integrasi.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 875,
                'cover' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvnMtmsNYrl0GUB-lHJT3iyAF0nj34OG3YCPMOTA&s=0',
                'collection' => 'Teori',
            ],
            [
                'title' => 'Fundamentals of Physics 9th Edition',
                'slug' => 'fundamentals_of_physics_9th_edition',
                'url' => 'https://drive.google.com/file/d/1qdVvzaXTi33231yyiFnC5jtq1q7A6TGl/view',
                'isbn' => '9780470561584',
                'penulis' => 'Jearl Walker',
                'penerbit' => 'Wiley',
                'tahun_terbit' => '2011',
                'abstrak' => 'Edisi Kesembilan yang baru dari “Prinsip-prinsip Fisika” Halliday, Resnick dan Walker telah direvisi secara strategis untuk fokus pada keterlibatan siswa, mendukung pemikiran kritis dan membawa siswa ke tingkat pemahaman fisika berikutnya.
                            Kunci dari dukungan Edisi Kesembilan terhadap pemikiran kritis dan pengembangan pemahaman konsep fisika adalah suara modern dari Earl Walker. Jearl Walker adalah seorang guru yang aktif, yang memahami tantangan yang dihadapi di ruang kelas saat ini, dan seorang komunikator sains yang terkenal di dunia kepada masyarakat umum. “Flying Circus of Physics” karya Jearl Walker merupakan buku klasik yang sangat digemari oleh para siswa dan instruktur fisika, dan materi dari buku ini diintegrasikan ke dalam buku Edisi Kesembilan ini untuk menarik perhatian siswa, melibatkan mereka, dan mendorong mereka untuk memecahkan fenomena dan konsep fisika dunia nyata yang mendasarinya, sebelum mereka memulai bagian yang lebih kuantitatif dari materi atau masalah.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 1330,
                'cover' => 'https://images.braincandy.com/covers/2/9781118115596.jpg',
                'collection' => 'Teori',
            ],
            [
                'title' => 'Calculus 9th Edition',
                'slug' => 'calculus_9th_edition',
                'url' => 'https://drive.google.com/file/d/1D4grkCnHZUOWEQWECzvGod2OJXCXkzNC/view',
                'isbn' => '9780132306331',
                'penulis' => 'Dale E. Varberg',
                'penerbit' => 'Pearson/Prentice Hall',
                'tahun_terbit' => '2007',
                'abstrak' => 'Teks kalkulus yang populer ini tetap menjadi buku kalkulus utama terpendek yang tersedia - namun mencakup semua materi yang dibutuhkan oleh, dan pada tingkat yang sesuai untuk, siswa di bidang teknik, sains, dan matematika. Keringkasan dan kejelasannya membantu siswa untuk fokus dan memahami konsep-konsep penting dalam kalkulus tanpa harus terjebak dan tersesat dalam detail yang berlebihan dan tidak perlu. Buku ini akurat, tanpa terlalu ketat, mutakhir tanpa menjadi kuno. Para penulis memanfaatkan teknologi komputasi, grafik, dan aplikasi secara efektif. Ideal untuk instruktur yang menginginkan perlakuan yang ringkas dan tidak bertele-tele.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 797,
                'cover' => 'https://i.ebayimg.com/images/g/hjYAAOSw3v5YpL3w/s-l600.jpg',
                'collection' => 'Teori',
            ],
            [
                'title' => 'Elektronika : Teori dan Penerapan',
                'slug' => 'elektronika_teori_dan_penerapan',
                'url' => 'https://drive.google.com/file/d/1ZOQrxm4hMpSqWOvItGqnNeeRsRDaQMBH/view',
                'isbn' => '9786029817478',
                'penulis' => 'Herman Dwi Surjono, Ph.D.',
                'penerbit' => 'Penerbit Cerdas Ulet Kreatif',
                'tahun_terbit' => '2007',
                'abstrak' => 'Buku ini diperuntukkan bagi siapa saja yang ingin mengetahui elektronika baik secara teori, konsep dan penerapannya. Pembahasan dilakukan secara komprehensif dan mendalam mulai dari pemahaman konsep dasar hingga ke taraf kemampuan untuk menganalisis dan mendesain rangkaian elektronika. Penggunaan matematika tingkat tinggi diusahakan seminimal mungkin, sehingga buku ini bias digunakan oleh berbagai kalangan. Pembaca dapat beraktivitas dengan mudah karena didukung banyak contoh soal dalam hamper setiap pokok bahasan serta latihan soal pada setiap akhir bab. Beberapa rangkaian penguat sedapat mungkin diambilkan dari pengalaman praktikum.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 197,
                'cover' => 'https://library.utp.ac.id/lib/minigalnano/createthumb.php?filename=images/docs/EL.jpg.jpg&width=200',
                'collection' => 'Teori',
            ],
            // TRMO
            [
                'title' => 'Modul ARV',
                'slug' => 'modul_arv',
                'url' => 'https://drive.google.com/file/d/1jSsU3vBfhr6xgA6Vs0jkTxd_1uQjpx7D/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => NULL,
                'tahun_terbit' => NULL,
                'abstrak' => 'Mikrokontrol AVR banyak digunakan saat ini, mengingat fitur cukup lengkap yang tergabung dalam sebuah chip tunggal. Dengan fitur yang ada dan disesuaikan dengan jenisnya, mikrokontrol keluarga ini sangat cocok untuk dikembangkan pada aplikasi-aplikasi kendali sederhana sampai dengan aplikasi-aplikasi kendali yang kompleks.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 56,
                'cover' => NULL,
                'collection' => 'TRMO',
            ],
            // TRO
            [
                'title' => 'Make: Getting Started with Arduino',
                'slug' => 'make_getting_started_with__arduino',
                'url' => 'https://drive.google.com/file/d/1yn-h3h4vZzF_b2lka_sOsvbc_LKuv3_6/view',
                'isbn' => '9781680456936',
                'penulis' => 'Massimo Banzi',
                'penerbit' => 'Dale Dougherty',
                'tahun_terbit' => '2022',
                'abstrak' => 'Arduino adalah platform pembuatan prototipe elektronik sumber terbuka yang merupakan jantung dari dunia Maker. Pengenalan menyeluruh ini, yang diperbarui untuk rilis Arduino IDE terbaru dan papan berbasis ARM baru, membantu Anda memulai pembuatan prototipe dengan segera. Mulai dari mendapatkan komponen yang diperlukan hingga memberikan sentuhan akhir pada proyek Anda, semua informasi yang Anda butuhkan ada di sini!',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 285,
                'cover' => 'https://www.makershed.com/cdn/shop/products/GSW_Arduino_4th_CVR.jpg?v=1646414000',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Praktik Digital dan Mikrokontroler',
                'slug' => 'praktik_digital_dan_mikrokontroler',
                'url' => 'https://drive.google.com/file/d/1q1H2F0WndBLTLky5llC3SC264eW5LUIc/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => NULL,
                'tahun_terbit' => NULL,
                'abstrak' => 'Modul Praktik Digital & Mikrokontroler terdiri dari dua modul yaitu Modul 1 Praktik Digital dan Modul 2 Praktik Mikrokontroler. Pada modul 1 Praktik Digital berisi pembahasan diantaranya rangkaian logika dasar, gerbang-gerbang logika, ‘nand’ sebagai gerbang universal serta aljabar boole. Setelah itu akan diuji rangkaian kombinasional yang merupakan rangkaian kombinasi sederhana dari gerbang- gerbang dasar, yang disusun untuk mendapatkan output sesuai dengan yang diinginkan. Untuk memahami lebih lanjut tentang aritmatika logika, unit jaringan dan pensaklaran akan dipraktikan rangkaian JK Flip-flop, multiplekser dan demultiplekser, rangkaian decoder dan encoder, dan yang terakhir adalah rangkaian ADC dan DAC.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 65,
                'cover' => NULL,
                'collection' => 'TRO',
            ],
            [
                'title' => 'Mikrokontroler Menggunakan Arduino IDE',
                'slug' => 'mikrokontroler_menggunakan_arduino_ide',
                'url' => 'https://drive.google.com/file/d/1qPbzVP2kx5TVtjVnkw6d5L_7L6ayANEZ/view',
                'isbn' => NULL,
                'penulis' => 'Abyanuddin Salam',
                'penerbit' => NULL,
                'tahun_terbit' => '2023',
                'abstrak' => 'Modul Praktik Mikrokontroler memuat beberapa praktikum yang melibatkan beberapa komponen seperti input output, motor servo, motor stepper, potensiometer, LCD I2C 20x4, buzzer, seven segment, keypad 4x4, motor DC, dan traffic light 1 way.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 28,
                'cover' => NULL,
                'collection' => 'TRO',
            ],
            [
                'title' => 'Elektronika Otomasi Industri (Modul 1)',
                'slug' => 'elektronika_otomasi_industri_modul1',
                'url' => 'https://drive.google.com/file/d/1F12qOQ2TaAnrr2Xk4tmk1QAfvaV27oX1/view',
                'isbn' => NULL,
                'penulis' => 'Abyanuddin Salam',
                'penerbit' => NULL,
                'tahun_terbit' => '2023',
                'abstrak' => 'Modul Praktik Mikrokontroler memuat beberapa praktikum yang membahas mengenai resistor dan resistansi, hukum ohm, hukum kirchhoff, persamaan mesh, teorema superposisi, teorema thivenin, jembatan wheatstone, transfer daya maksimum, dan pengamatan terhadap gelombang sinus.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 63,
                'cover' => NULL,
                'collection' => 'TRO',
            ],
            [
                'title' => 'Introducing SolidWorks',
                'slug' => 'introducing_solidworks',
                'url' => 'https://drive.google.com/file/d/12ue0QUYvNxoS5sK4pwoj_h58RA4JcPiG/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => 'Dassault Systèmes SolidWorks Corporation',
                'tahun_terbit' => '2011',
                'abstrak' => 'Dokumen ini diperuntukkan bagi pengguna baru SolidWorks. Dalam dokumen ini, Anda akan diperkenalkan dengan konsep dan proses desain dalam pendekatan tingkat tinggi. Pelajaran Langkah-demi-Langkah pada halaman 92 adalah pelatihan praktis yang memandu Anda melalui setiap langkah dalam proses dan menunjukkan menunjukkan hasilnya.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 120,
                'cover' => 'https://images.squarespace-cdn.com/content/v1/5c880b08809d8e5586fe04e1/1553534747021-TP6QWAYDAXT6ONG52Z0Z/54.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Learn AutoCAD: Mechanical Drawing Using AutoCAD 2016',
                'slug' => 'learn_autocad_mechanical_drawing_using_atuocad_2016',
                'url' => 'https://drive.google.com/file/d/1IhcWyv3WZuEWRTSW6Z-6iiyLPKlLmW4E/view',
                'isbn' => '9781533665799',
                'penulis' => 'David Martin',
                'penerbit' => NULL,
                'tahun_terbit' => '2016',
                'abstrak' => 'Selamat datang di Belajar AutoCAD!: Menggambar Mekanik Menggunakan AutoCAD 2016. Buku ini dirancang untuk memberikan pengenalan kepada anda mengenai Gambar Teknik menggunakan perangkat lunak AutoCAD 2016. Anda akan menerima pengenalan bagian 3D dari perangkat lunak dan menyelesaikan proyek dengan menggunakan bagian program ini. Setelah Anda menyelesaikan tutorial, Anda mungkin ingin mencetak gambar Anda dan mengumpulkannya ke dalam portofolio. Anda harus memiliki pengetahuan umum tentang proyeksi ortografi, linetype, ukuran vellum dan batas, simbologi pengelasan, dan praktik dimensi.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 314,
                'cover' => 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTAwJDfH6UNPumehlXD6ma41S6zRtqETJ1CCdo1jiYDXkS_Wqpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Application Note: PCB Design with EAGLE',
                'slug' => 'application_note_pcb_design_with_eagle',
                'url' => 'https://drive.google.com/file/d/1IhcWyv3WZuEWRTSW6Z-6iiyLPKlLmW4E/view',
                'isbn' => NULL,
                'penulis' => 'Kenji Aono',
                'penerbit' => 'CadSoft Computer GmbH',
                'tahun_terbit' => '2011',
                'abstrak' => 'Bagi para profesional, pelajar, dan penghobi, Papan Sirkuit Cetak (PCB) adalah komponen penting dalam menciptakan proyek kelistrikan yang bermanfaat. Kualitas dan kerumitan papan ini dapat bervariasi, mulai dari papan lapisan tunggal yang murah yang digunakan sebagai pengganti protoboard hingga papan di dalam pesawat ruang angkasa yang harus menjamin pengoperasian komponen penting dalam lingkungan yang paling keras. Dalam industri elektronik, karena komponen terus mengecil, pengemasan pemasangan di permukaan telah menjadi metode yang lebih disukai untuk mengirimkan komponen ke pelanggan. Perkembangan perangkat pemasangan di permukaan telah meningkatkan kebutuhan untuk membuat PCB berkualitas untuk membuat prototipe dan memvalidasi desain serta pengemasan akhir suatu produk.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 43,
                'cover' => 'https://cdn.hackaday.io/images/resize/600x600/5705491448916077669.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Piping and Instrumentation Diagram -P&ID',
                'slug' => 'piping_and_instrumentation_diagram_pid',
                'url' => 'https://drive.google.com/file/d/1Qw2F2bNkOx2Eg3dluoczkAEW_DUE0jBR/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => NULL,
                'tahun_terbit' => NULL,
                'abstrak' => 'Untuk membantu kelancaran pekerjaan instrumentasi dilapangan teknisi-teknisi instrumentasi harus memahami beberapa dokumen yang dapat menjelaskan lokasi, fungsi, dan parameter yang diukur atau dikontrol, spesifikasi, instalasi, kalibrasi, riwayat instrumen, Selain itu untuk penggambaran instrumen dalam diagram mengikuti standar internasional juga harus dipahami.',
                'bahasa' => 'Indonesia',
                'jumlah_halaman' => 30,
                'cover' => NULL,
                'collection' => 'TRO',
            ],
            [
                'title' => 'Advanced Industrial Automation',
                'slug' => 'advanced_industrial_automation',
                'url' => 'https://drive.google.com/file/d/1P6Yjg3-9B3vRGd2lpGirEp94u4C2Xikk/view',
                'isbn' => NULL,
                'penulis' => 'Himanshu Kumar',
                'penerbit' => NULL,
                'tahun_terbit' => '2020',
                'abstrak' => 'Buku ini akan membantu Anda untuk memahami otomasi industri dengan cara yang paling mudah. Isi buku disusun secara berurutan dan dijelaskan dengan baik. PLC, HMI, SCADA, AC Drive/ VFD, ANALOG, PID, dan Pengkabelan PLC. Setiap topik telah dijelaskan dengan contoh-contoh aplikasi industri. Lebih dari 100 contoh penyelesaian telah diberikan dalam buku ini. Bagian pemrograman telah dimulai dari awal dan diakhiri dengan program tingkat lanjut. Banyak trik yang telah dijelaskan untuk mempelajari pemrograman dengan cara yang paling mudah. Jika Anda mempelajari buku ini satu per satu, Anda akan mempelajari semua hal tentang otomasi industri. Materi program pelatihan jangka panjang (kursus yang mahal) telah dibahas dalam buku ini.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 311,
                'cover' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1591833956i/53947775.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'PLC Basics Course',
                'slug' => 'plc_basics_course',
                'url' => 'https://drive.google.com/file/d/1PIAawGKqZN7qEZNXY1JP8cNfAJlPcNqw/view',
                'isbn' => NULL,
                'penulis' => 'Himanshu Mishra',
                'penerbit' => 'Schneider Electric',
                'tahun_terbit' => '2010',
                'abstrak' => 'Modul ini membahas mengenai pemahaman tentang Central Processing Unit, struktur Memori Pengguna, opsi Perlindungan Program, CPU dan I/O Pemindaian Sistem juga akan dijelaskan.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 114,
                'cover' => NULL,
                'collection' => 'TRO',
            ],
            [
                'title' => 'Introduction to PLC Programming and Implementation from Relay Logic to PLC Logic',
                'slug' => 'introduction_to_plc_programming_and_implementation',
                'url' => 'https://drive.google.com/file/d/1Q3bLu7gTLsEfVVjrXnogkQaBrVB57sDL/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => 'Industrial Text and Video Company',
                'tahun_terbit' => '1999',
                'abstrak' => 'Berikut ini adalah referensi PLC yang berharga yang dapat Anda gunakan sekarang juga. Referensi khusus ini diambil dari buku teks kami yang memenangkan penghargaan-Programmable Controllers: Teori dan Implementasi, Edisi ke-2. Di dalamnya, Anda akan mendapatkan gambaran umum tentang bagaimana logika relai dapat diubah menjadi logika PLC. Ada juga banyak contoh, tabel, dan diagram tangga untuk membantu menjelaskan topik.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 76,
                'cover' => 'https://img.yumpu.com/44829310/1/500x640/programmable-controllers-theory-and-implementation.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Programmable Logic Controllers - Programming Methods and Applications',
                'slug' => 'plc_programming_methods_and_applications',
                'url' => 'https://drive.google.com/file/d/1aQJGdvPhvgm9R0n8bhE1O6L_7-K5nfRd/view',
                'isbn' => NULL,
                'penulis' => 'John R. Hackworth',
                'penerbit' => NULL,
                'tahun_terbit' => NULL,
                'abstrak' => 'Pembaca teks ini harus memiliki pemahaman menyeluruh tentang rangkaian ac dan dc dasar, perangkat elektronik (termasuk thyristor), pengetahuan tentang gerbang logika dasar, flip flop, dan aljabar Boolean, serta aljabar dan trigonometri perguruan tinggi. Meskipun pengetahuan tentang kalkulus akan meningkatkan pemahaman tentang kontrol PID, namun tidak diperlukan untuk mempelajari cara menyetel PID dengan benar.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 272,
                'cover' => 'https://cdn.slidesharecdn.com/ss_thumbnails/plcprogrammingmethodsandapplicationsbyjohnrhackworthandfrederickdhackworthjr-220612064218-46632bb9-thumbnail.jpg?width=640&height=640&fit=bounds',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Programmable Controllers Theory and Implementation Second Edition',
                'slug' => 'programmable_controllers_theory_and_implementation_second_edition',
                'url' => 'https://drive.google.com/file/d/1vhIZIpcsavlLel9hgRNZRWlYKRk3f4Tl/view',
                'isbn' => '094410732X',
                'penulis' => 'L. A. Bryan',
                'penerbit' => 'Industrial Text Company',
                'tahun_terbit' => '1997',
                'abstrak' => 'Edisi baru ini telah menjadi pengalaman pembelajaran yang padat karya bagi semua yang terlibat. Seperti halnya tugas yang begitu besar, kami tidak akan pernah bisa melakukannya sendiri. Oleh karena itu, kami ingin mengucapkan terima kasih kepada perusahaan-perusahaan berikut ini atas bantuan mereka dalam mewujudkan buku ini: Allen-Bradley Company-Industrial Computer Group, ASI-USA, B&R Industrial Automation, Bailey Controls Company, DeviceNet Vendors Association, ExperTune Software, Fieldbus Foundation, Hoffman Engineering Company, Honeywell-MicroSwitch Division, LANcity-Cable Modem Division of Bay Networks, Mitsubishi Electronics, Omron Electronics, Phoenix Contact, PLC Direct, PMC/BETA LP, Profibus Trade Organization, Schaevitz Engineering Company, Siemens Automation, Square D Company, Thermometrics, dan Wago.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 1047,
                'cover' => 'https://images.tokopedia.net/img/cache/700/hDjmkQ/2023/8/24/9c3c7dd1-9866-440e-b664-6abadc67bb8c.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Data Acquisition Handbook',
                'slug' => 'data_acquisition_handbook',
                'url' => 'https://drive.google.com/file/d/1NNMJjCJId6fPn0HVK5lzrRMlYeERJe8-/view',
                'isbn' => NULL,
                'penulis' => NULL,
                'penerbit' => 'Measurement Computing Corporation',
                'tahun_terbit' => '2012',
                'abstrak' => 'Sistem akuisisi data mengukur, menyimpan, menampilkan, dan menganalisis informasi yang dikumpulkan dari berbagai perangkat. Sebagian besar pengukuran memerlukan transduser atau sensor, perangkat yang mengubah kuantitas fisik yang dapat diukur menjadi sinyal listrik. Contohnya termasuk suhu, regangan, akselerasi, tekanan, getaran, dan suara. Yang lainnya adalah kelembapan, aliran, level, kecepatan, muatan, pH, dan komposisi kimia.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 145,
                'cover' => 'https://img.yumpu.com/33318965/1/500x640/data-acquisition-handbook-from-measurement-computing.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Mechatronics Electronic Control Systems in Mechanical and Electrical Engineering',
                'slug' => 'mechatronics_electronic_control_systems_in_mechanical_and_electrical_engineering',
                'url' => 'https://drive.google.com/file/d/1M_y3kONPgjD4FdrHe6CO77tqaa1rYsNM/view',
                'isbn' => '9781292081595',
                'penulis' => 'Wiiliam Bolton',
                'penerbit' => 'Pearson Education',
                'tahun_terbit' => '2015',
                'abstrak' => 'Edisi keenam telah melibatkan restrukturisasi bagian-bagian penyusun buku ini karena beberapa pengguna merasa bahwa urutan bab tidak sesuai dengan urutan pengajaran secara umum. Oleh karena itu, edisi baru ini telah memindahkan bagian model sistem sehingga muncul setelah sistem mikroprosesor. Perubahan lain termasuk dimasukkannya materi tentang Arduino dan penambahan lebih banyak topik dalam bab Sistem Mekatronika.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 663,
                'cover' => 'https://catalog.umj.ac.id/lib/minigalnano/createthumb.php?filename=images/docs/download_%2865%29.jpg.jpg&width=200',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Sensors For Mechatronics',
                'slug' => 'sensors_for_mechatronics',
                'url' => 'https://drive.google.com/file/d/1p3YVFOssoOJia1EZdeR20mVksRtspjXL/view',
                'isbn' => '9780128138106',
                'penulis' => 'Paul Regtien',
                'penerbit' => 'Mara Conner',
                'tahun_terbit' => '2018',
                'abstrak' => 'Bab pengantar ini memberikan pandangan umum tentang sensor. Pada bagian pertama, fungsi sensor, nomenklatur sensor, dan properti global disajikan, sebagai pendahuluan untuk diskusi yang lebih mendalam mengenai performa sensor dan prinsip pengoperasian dalam bab berikutnya. Menurut jumlah informasi yang dapat dikandung sinyal output, tiga kategori sensor dibedakan dan masing-masing dibahas secara singkat: sensor biner, analog, dan gambar. Kategori yang terakhir ini terdiri atas sensor gambar optik, akustik, dan taktil. Bagian kedua menyajikan pendekatan umum untuk proses pemilihan sensor untuk aplikasi tertentu. Bagian terakhir memperkenalkan platform untuk arsitektur sensor dalam lingkungan tertanam dan berfungsi sebagai dasar untuk solusi penginderaan tertanam spesifik yang dibahas dalam bab-bab berikutnya.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 451,
                'cover' => 'https://m.media-amazon.com/images/I/61xiiehSkyL._AC_UF1000,1000_QL80_.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Control of Mechatronic Systems',
                'slug' => 'control_of_mechatronic_systems',
                'url' => 'https://drive.google.com/file/d/11XWqqNICcsdSFYVA-cbLOXyY5C7wqX5I/view',
                'isbn' => '9781785611452',
                'penulis' => 'Levent G ̈uven ̧c',
                'penerbit' => 'The Institution of Engineering and Technology',
                'tahun_terbit' => '2017',
                'abstrak' => 'Buku ini dikembangkan dari disertasi doktoral penulis kedua, Prof. BilinAksun-Güvenç. Prof. Levent Güvenç dan Prof. BilinAksun-Güvenç telah mengajarkan materi dalam buku ini sebagai mata kuliah tingkat pascasarjana selama bertahun-tahun di Istanbul Technical University, dan kemudian di Istanbul Okan University. Baru-baru ini pada tahun 2016, Dr. Burak Demirel telah mengajarkan materi dalam buku ini di Universitas Paderborn, dan Prof. Levent Güvenç telah mengajarkan materi dalam buku ini di Ohio State University. Audiens untuk kursus-kursus ini adalah mahasiswa pascasarjana di bidang Teknik Mekatronika, Teknik Mesin, Teknik Elektro, Teknik Dirgantara, dan Teknik Kontrol yang telah mengambil setidaknya satu, lebih disukai dua mata kuliah tentang analisis dan desain sistem kontrol, termasuk beberapa eksposur ke sistem waktu diskrit.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 217,
                'cover' => 'https://imgv2-2-f.scribdassets.com/img/document/520004192/original/e34696a952/1720861242?v=1',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Control Systems Engineering 6th Edition',
                'slug' => 'control_systems_engineering_6th_edition',
                'url' => 'https://drive.google.com/file/d/1Fncd5OnzYREGkPeTISXqp4VIQFo4zRJ8/view',
                'isbn' => '9780470547564',
                'penulis' => 'Norman S. Nise',
                'penerbit' => 'John Wiley & Sons, Inc.',
                'tahun_terbit' => '2011',
                'abstrak' => 'Sangat dihargai karena aksesibilitas dan fokusnya pada aplikasi praktis, Teknik Sistem Kontrol menawarkan kepada para mahasiswa pengenalan yang komprehensif terhadap desain dan analisis sistem umpan balik yang mendukung teknologi modern. Melampaui teori dan matematika abstrak untuk menerjemahkan konsep-konsep utama ke dalam desain sistem kontrol fisik, teks ini menyajikan studi kasus dunia nyata, pertanyaan bab yang menantang, dan penjelasan terperinci dengan penekanan pada desain berbantuan komputer. Ilustrasi yang berlimpah memudahkan pemahaman, dengan lebih dari 800 foto, diagram, grafik, dan tabel yang dirancang untuk membantu siswa memvisualisasikan konsep-konsep yang kompleks.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 984,
                'cover' => 'https://i.pinimg.com/736x/9d/ee/85/9dee85ffe1a21abb705fb05d2164c455.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Control Theory A guided tour 3rd Edition',
                'slug' => 'control_theory_a_guided_tour_3rd_edition',
                'url' => 'https://drive.google.com/file/d/1i-4Zac65mIULcQ4CTorKdAAEa0oTqneB/view',
                'isbn' => '9781849192286',
                'penulis' => 'James Ron Leigh',
                'penerbit' => 'The Institution of Engineering and Technology',
                'tahun_terbit' => '2012',
                'abstrak' => 'Penggunaan kontrol semakin meluas, saat ini Anda dapat menemukan sistem kontrol di mana-mana, di rumah, mobil, pabrik, dan instrumen ilmiah. Kontrol juga merupakan elemen penting dari semua proses kehidupan. Oleh karena itu, kebutuhan untuk mengetahui tentang kontrol semakin meluas. Dua edisi pertama dari buku yang tidak biasa ini telah menjangkau khalayak luas, saya berharap edisi ketiga ini akan mengikuti jejak mereka. Secara pribadi saya menikmati membacanya, meskipun saya tidak selalu setuju dengan pandangan penulis.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 472,
                'cover' => 'https://image.ebooks.com/cover/1117244.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Manual for Modern Control Engineering 5th Edition',
                'slug' => 'manual_for_modern_control_engineering_5th_edition',
                'url' => 'https://drive.google.com/file/d/1pTWK1j8w7hzWUXQM7IZm5-Gaiq_xVDSR/view',
                'isbn' => NULL,
                'penulis' => 'Katsuhiko Ogata',
                'penerbit' => 'Pearson Education',
                'tahun_terbit' => '2010',
                'abstrak' => 'Buku ini merupakan perlakuan modern terhadap teori kontrol klasik dan konsep aplikasi. Secara teoritis, buku ini didasarkan pada pendekatan ruang keadaan, di mana konsep-konsep utama telah diturunkan hanya dengan menggunakan pengetahuan dari mata kuliah pertama dalam aljabar linier. Sistem kontrol waktu kontinu dan waktu diskrit diperlakukan secara bersamaan dengan sedikit penekanan pada sistem waktu kontinu, terutama di bidang desain pengontrol.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 240,
                'cover' => 'https://image.slidesharecdn.com/moderncontrolengineering5thedsolutionmanual2010-181112184617/85/Modern-control-engineering-5th-ed-solution-manual-2010-1-320.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Modern Control Engineering 5th Edition',
                'slug' => 'modern_control_engineering_5th_edition',
                'url' => 'https://drive.google.com/file/d/1JIdy1BYfpJ7oLRpu_cTDjvcppP8i2YvR/view',
                'isbn' => '9780136156734',
                'penulis' => 'Katsuhiko Ogata',
                'penerbit' => 'Pearson Education',
                'tahun_terbit' => '2010',
                'abstrak' => 'Buku ini merupakan perlakuan modern terhadap teori kontrol klasik dan konsep aplikasi. Secara teoritis, buku ini didasarkan pada pendekatan ruang keadaan, di mana konsep-konsep utama telah diturunkan hanya dengan menggunakan pengetahuan dari mata kuliah pertama dalam aljabar linier. Sistem kontrol waktu kontinu dan waktu diskrit diperlakukan secara bersamaan dengan sedikit penekanan pada sistem waktu kontinu, terutama di bidang desain pengontrol.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 905,
                'cover' => 'https://image.slidesharecdn.com/moderncontrolengineering5thedsolutionmanual2010-181112184617/85/Modern-control-engineering-5th-ed-solution-manual-2010-1-320.jpg',
                'collection' => 'TRO',
            ],
            [
                'title' => 'Solved Problems in Dynamical Systems and Control',
                'slug' => 'solved_problems_in_dynamical_systems_and_control',
                'url' => 'https://drive.google.com/file/d/1Twsgeds5RdTJ89gMQmruagTCDJ0NBKcR/view',
                'isbn' => '9781785611759',
                'penulis' => 'J. Tenreiro Machado',
                'penerbit' => 'The Institution of Engineering and Technology',
                'tahun_terbit' => '2016',
                'abstrak' => 'Buku ini menyajikan kumpulan latihan soal-soal sistem dinamik, pemodelan dan kontrol. Setiap topik yang dibahas meliputi ringkasan latar belakang teori, soal-soal beserta solusinya, dan latihan-latihan lebih lanjut. Topik-topik yang dibahas meliputi: aljabar diagram blok dan fungsi transfer sistem; model matematika; analisis sistem kontinu dalam domain waktu; analisis lokus akar; analisis domain frekuensi; sintesis kontroler PID; analisis ruang keadaan sistem kontinu; sintesis kontroler dengan penempatan kutub; sistem waktu diskrit dan transformasi z; analisis sistem non-linier dengan metode fungsi penjelas; analisis sistem non-linier dengan metode bidang fasa; serta sistem dan kontroler orde pecahan. Berdasarkan masalah dan solusi yang telah dicoba dan diuji yang digunakan penulis dalam mengajar lebih dari 500 mahasiswa setiap tahunnya, buku ini merupakan bacaan penting bagi mahasiswa tingkat lanjut yang mengambil mata kuliah pemodelan dan kontrol di bidang teknik, matematika terapan, biomatematika, dan fisika.',
                'bahasa' => 'Inggris',
                'jumlah_halaman' => 448,
                'cover' => 'https://im2.book.com.tw/image/getImage?i=https://www.books.com.tw/img/F01/384/95/F013849503.jpg&v=609a8fa4k&w=375&h=375',
                'collection' => 'TRO',
            ],
            // TRIN
        ];

        DB::table('pustakas')->insert($pustaka);
    }
}
